In [46]:
import numpy as np

array = np.array([[1,2,3], [4,5,6]])

print("array =\n", array)
print("array dimension =", array.ndim)
print("array shape =", array.shape)
print("array item size =", array.size)

array =
 [[1 2 3]
 [4 5 6]]
array dimension = 2
array shape = (2, 3)
array item size = 6


In [47]:
# array create

array = np.array([1,2,3], dtype=int)
print(array, array.dtype)

array = np.array([[1,2,3],[4,5,6]])
print(array)

array = np.zeros((2,3))
print(array)

array = np.ones((2,3))
print(array)

array = np.arange(12).reshape((3,4))
print(array)

# 线段 0 ~ 10 分成 11 个点，10 个线段
array = np.linspace(0, 10, 11)
# 打印的是点
print(array)


[1 2 3] int64
[[1 2 3]
 [4 5 6]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [48]:
# numpy 基础运算

a = np.array([2,3,4,5])
b = np.arange(4)
# 基础运算
c = a * b
print(c)
# 三角函数
d = np.cos(a)
print(d)
# 判断数组内元素大小情况
print(d > 0)
# 矩阵点乘
aa = a.reshape((2,2))
bb = b.reshape((2,2))
cc = np.dot(aa, bb)
print(cc)
# 随机矩阵
rdm = np.random.random((2,4))
print(rdm)
print(np.sum(rdm)) # 默认全部元素
print(np.max(rdm))
print(np.min(rdm))

print(np.sum(rdm, axis=0)) # 按列分别求和
print(np.sum(rdm, axis=1)) # 按行分别求和


[ 0  3  8 15]
[-0.41614684 -0.9899925  -0.65364362  0.28366219]
[False False False  True]
[[ 6 11]
 [10 19]]
[[0.55782039 0.07670042 0.79355649 0.92523599]
 [0.06649641 0.63314687 0.40811454 0.05885954]]
3.519930652349897
0.9252359899829072
0.05885954037861252
[0.6243168  0.70984728 1.20167104 0.98409553]
[2.35331329 1.16661736]


In [ ]:
# 元素索引
A = np.arange(2,14).reshape((3,4))
print(np.argmax(A))
print(np.argmin(A))
# 中位数
print(np.median(A))
# 平均值
print(np.average(A))
# 前缀和
print(np.cumsum(A))
# 差分
print(np.diff(A))
# 非零数位置
print(np.nonzero(A))

11
0
7.5
7.5
[ 2  5  9 14 20 27 35 44 54 65 77 90]


In [53]:
# 转置
A = np.arange(14,2,-1).reshape((3,4))
print(A)
print(np.transpose((A)))

# 排序
print(np.sort(A))

# 限制大小
print(np.clip(A,5,9))

# 按行列计算平均值
print(np.mean(A,axis=1))

[[14 13 12 11]
 [10  9  8  7]
 [ 6  5  4  3]]
[[14 10  6]
 [13  9  5]
 [12  8  4]
 [11  7  3]]
[[11 12 13 14]
 [ 7  8  9 10]
 [ 3  4  5  6]]
[[9 9 9 9]
 [9 9 8 7]
 [6 5 5 5]]
[12.5  8.5  4.5]


In [61]:
# 索引
B = np.arange(2,14).reshape((3,4))
print(B)
print(B[1][2])
print(B[1,2])

# 遍历行
for row in B:
    print(row)

# 遍历列
for col in B.T:
    print(col)

# 遍历元素
for item in B.flat:
    print(item)

[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]
8
8
[2 3 4 5]
[6 7 8 9]
[10 11 12 13]
[ 2  6 10]
[ 3  7 11]
[ 4  8 12]
[ 5  9 13]
2
3
4
5
6
7
8
9
10
11
12
13
