In [4]:
# Textbook: Principles and Practices of Machine Learning
# Temperature dataset
# Author: Zhe Chen (ml_iot@163.com), 2021

import pandas
import numpy as np

# load dataset
df = pandas.read_csv('temperature_dataset.csv')
data = np.array(df)

# print("DataFrame (df) 的前几行:")
# print(df.head())
# print("\nNumPy 数组 (data) 的前几行:")
# print(data[:5]) # 打印前5行
# print("\nNumPy 数组的形状 (data.shape):")
# print(data.shape)

DataFrame (df) 的前几行:
   -0.7  -2.3  0.1  -2.3.1  -0.9
0  -1.1  -2.5 -0.3    -2.7  -1.1
1  -1.1  -3.0 -0.7    -3.2  -1.7
2  -1.4  -3.6 -1.0    -3.3  -2.1
3  -2.0  -3.5 -1.3    -4.1  -2.4
4  -2.2  -4.5 -1.8    -4.2  -2.8

NumPy 数组 (data) 的前几行:
[[-1.1 -2.5 -0.3 -2.7 -1.1]
 [-1.1 -3.  -0.7 -3.2 -1.7]
 [-1.4 -3.6 -1.  -3.3 -2.1]
 [-2.  -3.5 -1.3 -4.1 -2.4]
 [-2.2 -4.5 -1.8 -4.2 -2.8]]

NumPy 数组的形状 (data.shape):
(3959, 5)
